@extends('layouts.app')
@section('title', 'Progress and evidence')
@section('content')
<a class="back" href="{{ route('delivery.show',$enrolment->id) }}">Back to learning plan</a>
<div class="page-heading"><div><p class="eyebrow">{{ $enrolment->member->name }}</p><h1>Progress and evidence</h1><p>Approved evidence informs progress. Missing samples are never treated as zero.</p></div></div>
@forelse($metrics as $metric)
@php($snapshot=$snapshots[$metric->id])
<section class="panel"><h2>{{ $metric->definition['name'] }}</h2><p>{{ $metric->definition['rationale'] }}</p><p>Target {{ $metric->definition['target'] }} {{ $metric->definition['unit'] }} · {{ str_replace('_',' ',$metric->definition['evidence_type']) }} · definition {{ $metric->version }}</p>
<p><strong>{{ $snapshot ? str_replace('_',' ',$snapshot->status) : 'Insufficient evidence' }}</strong> · {{ $snapshot?->value ?? 'No sufficient result' }} · {{ $snapshot?->sample_count ?? 0 }}/{{ $metric->definition['sample_minimum'] }} required samples</p>
@if($snapshot)<details><summary>Evidence lineage</summary><p>Snapshot {{ $snapshot->id }} · {{ $snapshot->created_at }}. Later changes do not rewrite this snapshot.</p><ul>@foreach($snapshot->source_ids as $source)<li>{{ $source }}</li>@endforeach</ul></details>@endif
@if($coordinator)
<form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="snapshot"><input type="hidden" name="metric" value="{{ $metric->id }}"><button class="secondary">Refresh evidence snapshot</button></form>
@if($metric->definition['formula'] === 'manual_mean')<details><summary>Record workplace evidence</summary><form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="observe"><input type="hidden" name="metric" value="{{ $metric->id }}"><label>Observed value<input name="value" type="number" step="any" required></label><label>Evidence reference<textarea name="evidence" minlength="10" required></textarea></label><label>Reason<input name="reason" minlength="8" required></label><button class="primary">Record evidence</button></form></details>@endif
<details><summary>Revise future KPI definition</summary><form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="revise"><input type="hidden" name="metric" value="{{ $metric->id }}">
@foreach(['name','rationale','unit','target','baseline'] as $field)<label>{{ ucfirst($field) }}<input name="definition[{{ $field }}]" value="{{ $metric->definition[$field] }}" required></label>@endforeach
<label>Direction<select name="definition[direction]">@foreach(['higher','lower','band'] as $direction)<option @selected($metric->definition['direction']===$direction)>{{ $direction }}</option>@endforeach</select></label><label>Upper target (band only)<input type="number" step="any" name="definition[upper_target]"></label>
<label>Formula<select name="definition[formula]"><option value="approved_grade_mean" @selected($metric->definition['formula']==='approved_grade_mean')>Approved grade mean (percent)</option><option value="manual_mean" @selected($metric->definition['formula']==='manual_mean')>Observed evidence mean</option></select></label>
<label>Evidence type<select name="definition[evidence_type]"><option value="demonstrated_competence">Demonstrated competence</option><option value="workplace_outcome" @selected($metric->definition['evidence_type']==='workplace_outcome')>Workplace outcome</option></select></label><label>Minimum samples<input type="number" min="1" max="100" name="definition[sample_minimum]" value="{{ $metric->definition['sample_minimum'] }}" required></label>
<label>Effective from (UTC)<input type="datetime-local" name="effective" required></label><label>Reason<input name="reason" minlength="8" required></label><button class="primary">Save future definition</button></form></details>
@endif</section>@empty<p class="notice">KPI definitions become available after programme activation.</p>@endforelse
@if($coordinator && $metrics->count())
<section class="panel"><h2>Support suggestions</h2><p>Suggestions never change targets or increase allocated hours. Synthetic AI output is demonstration content.</p><form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="suggest"><button class="secondary">Suggest actions with AI</button></form>
@foreach($suggestions as $suggestion)<h3>{{ ucfirst($suggestion->status) }} · {{ $suggestion->created_at }}</h3><ul>@foreach($suggestion->actions ?? [] as $action)<li>{{ $action }}</li>@endforeach</ul>@endforeach</section>
<section class="panel"><h2>Adapt future lessons</h2><p>Evidence from block N can support N+2 or a later eligible block. Started or frozen lessons remain unchanged.</p><form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="propose"><label>Approved evidence block<input name="evidence_block" type="number" min="1" max="12" required></label><label>Support reason<input name="reason" minlength="8" required></label><button class="secondary">Propose adaptation with AI</button></form></section>@endif
@foreach($proposals as $proposal)<section class="panel"><h2>{{ str_replace('_',' ',$proposal->status) }} · {{ $proposal->block ? 'Block '.$proposal->block->number : 'Final support' }}</h2><p>{{ $proposal->reason }}</p><p>Evidence block {{ $proposal->evidence_block }} · {{ $proposal->policy_version }}</p>
@if($proposal->status==='final_support')<p>No future block is eligible. Discuss targeted final support or a follow-on programme without changing completed history.</p>@endif
@foreach($proposal->replacement['lessons'] ?? [] as $lesson)<h3>{{ $lesson['title'] }}</h3><p>{{ $lesson['activity'] }}</p>@endforeach
@if($coordinator && $proposal->status==='provisional')<form method="post" action="{{ route('progress.act',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="approve"><input type="hidden" name="proposal" value="{{ $proposal->id }}"><input type="hidden" name="base" value="{{ $proposal->learning_block_id }}"><label>Review rationale<input name="reason" minlength="8" required></label><button class="primary">Approve this future version</button></form>@endif</section>@endforeach
@endsection
