@extends('layouts.app')
@section('title', 'Submission receipt')
@section('content')
<a class="back" href="{{ route('delivery.show',$enrolment->id) }}">Back to learning plan</a>
<h1>Submission receipt</h1><p>{{ $submission->id }}</p><p>Attempt {{ $submission->attempt }} · {{ $submission->created_at }} · {{ str_replace('_',' ',$submission->status) }}</p>
@if($changeDecision)<section class="panel"><h2>Requested changes</h2><p>{{ $changeDecision->reason }}</p><ul>@foreach($changeDecision->scores['criteria'] as $criterion)<li>{{ $criterion['feedback'] }}</li>@endforeach</ul><p>Return to the lesson, update your saved work and submit a new attempt.</p></section>@endif
@if($submission->quiz_snapshot)<section class="panel"><h2>Submitted answers</h2>@foreach($submission->quiz_snapshot['questions'] as $question)<p>{{ $question['prompt'] }}: {{ $question['options'][$submission->answers[$question['id']]??'']??'Not answered' }}</p>@endforeach</section>@endif
<section class="panel"><h2>Submitted work</h2><p class="preserve-lines">{{ $submission->body }}</p><ul>@foreach($submission->files as $id)<li><a href="{{ route('files.download',$id) }}">Download submitted evidence</a></li>@endforeach</ul><p>This submitted snapshot is preserved. New work creates a new attempt.</p></section>
@if($approved)<section class="panel"><h2>Approved feedback</h2><p>Score: {{ $approved->decision->total }} / 100</p><p>{{ $approved->decision->reason }}</p><ul>@foreach($approved->decision->scores['criteria'] as $criterion)<li>{{ $criterion['feedback'] }} · {{ $criterion['score'] }}/100</li>@endforeach</ul></section>@elseif(!$coordinator)<p class="notice">Awaiting review. Provisional scores are not official results.</p>@endif
@if($coordinator)
<section class="panel"><h2>Grading attempts</h2>@forelse($grades as $grade)<details open><summary>Grade attempt {{ $grade->version }} · {{ str_replace('_',' ',$grade->status) }}</summary>@if($grade->result)<p>Provisional total: {{ $grade->total ?? 'Insufficient evidence' }}</p><ul>@foreach($grade->result['criteria'] as $criterion)<li>{{ $criterion['feedback'] }} · {{ $criterion['score'] }}</li>@endforeach</ul>@endif
@if($grade->status === 'provisional')<form method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="expected_version" value="{{ $submission->version }}"><input type="hidden" name="grade_id" value="{{ $grade->id }}"><label>Review rationale<input name="reason" minlength="8" required></label><button class="primary" name="action" value="approve">Approve grade</button> <button class="secondary" name="action" value="changes">Request changes</button></form>@endif</details>@empty<p>No grading attempt yet. You can request provisional analysis or assess the evidence directly.</p>@endforelse
<form method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="action" value="grade"><input type="hidden" name="expected_version" value="{{ $submission->version }}"><label>Grading or regrading notes<input name="reason" minlength="8" required></label><button class="secondary">Request provisional grading</button></form></section>
<section class="panel"><h2>Human assessment or override</h2><form method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="action" value="manual"><input type="hidden" name="expected_version" value="{{ $submission->version }}">
@foreach($submission->rubric['criteria'] as $index=>$criterion)<fieldset class="lesson"><legend>{{ $criterion['label'] }}</legend><label>Score for criterion {{ $index+1 }}<input name="scores[{{ $index }}][score]" type="number" min="0" max="100" step="0.01" required></label><label>Evidence and feedback for criterion {{ $index+1 }}<textarea name="scores[{{ $index }}][feedback]" required></textarea></label><label><input type="checkbox" name="scores[{{ $index }}][insufficient]" value="1">Insufficient evidence</label></fieldset>@endforeach
<label>Decision<select name="outcome"><option value="approved">Approve</option><option value="changes_requested">Request more evidence or changes</option></select></label><label>Decision rationale<input name="reason" minlength="8" required></label><button class="primary">Record human decision</button></form></section>
@else
@if($submission->approved_grade_id)<form class="panel" method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="expected_version" value="{{ $submission->version }}"><input type="hidden" name="action" value="appeal"><label>Why you are requesting another review<textarea name="reason" minlength="8" required></textarea></label><button class="secondary">Request an appeal</button></form>
@elseif($submission->status !== 'withdrawn')<form class="panel" method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="expected_version" value="{{ $submission->version }}"><input type="hidden" name="action" value="withdraw"><label>Withdrawal reason<input name="reason" minlength="8" required></label><button class="secondary">Withdraw pending attempt</button></form>@endif
@endif
@foreach($appeals as $appeal)<section class="panel"><h2>Appeal · {{ $appeal->status }}</h2><p>{{ $appeal->reason }}</p><p>{{ $appeal->resolution ?: ($appeal->reviewer_id ? 'Assigned to an alternate reviewer.' : 'An administrator must assign an alternate reviewer.') }}</p>
@if($appeal->status === 'open' && $appeal->reviewer_id === auth()->id())<form method="post" action="{{ route('submission.review',$submission->id) }}">@csrf<input type="hidden" name="action" value="uphold"><input type="hidden" name="expected_version" value="{{ $submission->version }}"><label>Independent review rationale<input name="reason" minlength="8" required></label><button class="secondary">Uphold existing decision</button></form><p>To replace the decision, record a new human assessment above.</p>@endif</section>@endforeach
@endsection
