@extends('layouts.app')
@section('title', 'Learning plan')
@section('content')
<a class="back" href="{{ route('enrolments.show',$enrolment->id) }}">Back to enrolment</a>
<p><a class="secondary" href="{{ route('progress.show',$enrolment->id) }}">Progress, KPIs and future support</a></p>
<div class="page-heading"><div><p class="eyebrow">{{ $enrolment->member->name }}</p><h1>Today and learning plan</h1><p>{{ $enrolment->title }} · {{ $enrolment->timezone }}</p></div><span class="badge">{{ ucfirst($enrolment->status) }}</span></div>
@if($enrolment->status === 'ready' && $coordinator)<section class="panel"><h2>Activate the approved programme</h2><p>Every block must have an approved baseline. Activation preserves the exact lessons and rubric for submitted work.</p><form method="post" action="{{ route('delivery.activate',$enrolment->id) }}">@csrf<input type="hidden" name="expected_version" value="{{ $enrolment->version }}"><label>Activation reason<input name="reason" minlength="8" required></label><button class="primary">Activate programme</button></form></section>@endif
@forelse($blocks as $block)<section class="panel"><h2>Block {{ $block->number }} · {{ $block->content['start'] }}</h2><p>{{ $block->content['objective'] }}</p><p class="subtle">Version {{ $block->version }} · {{ $block->started_at ? 'Started; version locked' : 'Upcoming or available' }}</p><ul class="file-list">@foreach($block->content['lessons'] as $index=>$lesson)<li><div><a href="{{ route('delivery.lesson',[$block->id,$index]) }}">{{ $lesson['title'] }}</a><small>{{ $lesson['date'] }} · {{ $lesson['reading']+$lesson['practice']+$lesson['assessment']+$lesson['revision'] }} minutes @if($lesson['date'] === now($enrolment->timezone)->toDateString()) · Today @endif</small></div></li>@endforeach</ul>
@if($coordinator && !$block->started_at && $enrolment->status === 'active')<details><summary>Authorise early start</summary><form method="post" action="{{ route('delivery.early',$block->id) }}">@csrf<label>Early-start reason<input name="reason" minlength="8" required></label><button class="secondary">Authorise and lock block</button></form></details>@endif
</section>@empty<p class="notice">Lessons become available after the coordinator activates an approved programme.</p>@endforelse
<section class="panel"><h2>Submissions and review</h2><ul>@forelse($submissions as $submission)<li><a href="{{ route('submission.show',$submission->id) }}">Attempt {{ $submission->attempt }} · {{ $submission->created_at }} · {{ str_replace('_',' ',$submission->status) }}</a></li>@empty<li>No submissions yet.</li>@endforelse</ul></section>
@if($coordinator && in_array($enrolment->status,['active','paused']))
<section class="panel"><h2>Programme decisions</h2>
@if($enrolment->status==='active')
<details><summary>Pause for leave or review</summary><form method="post" action="{{ route('delivery.lifecycle',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="pause"><input type="hidden" name="expected_version" value="{{ $enrolment->version }}"><label>Pause reason<input name="reason" minlength="8" required></label><button class="secondary">Pause programme</button></form></details>
<details><summary>Confirm completion</summary><p>Every required lesson must have approved evidence and all current KPI targets must have sufficient evidence. Confirm the member can demonstrate the target capability.</p><form method="post" action="{{ route('delivery.lifecycle',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="complete"><input type="hidden" name="expected_version" value="{{ $enrolment->version }}"><label>Capability confirmation and evidence rationale<textarea name="reason" minlength="8" required></textarea></label><button class="primary">Confirm programme completion</button></form></details>
@else
<p>Started lessons and submitted attempts retain their original versions. Preview an explicit schedule for upcoming lessons before resuming.</p>
<form method="post" action="{{ route('delivery.lifecycle',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="preview"><input type="hidden" name="expected_version" value="{{ $enrolment->version }}"><label>Move unstarted blocks forward (weeks; zero keeps dates)<input name="weeks" type="number" min="0" max="52" value="1" required></label><label>Schedule reason<input name="reason" minlength="8" required></label><button class="secondary">Preview resume schedule</button></form>
@foreach($changes as $change)<h3>Schedule preview · {{ $change->created_at }}</h3><p>{{ $change->reason }}</p><ul>@foreach($change->preview['replacements'] as $replacement)<li>Block {{ $replacement['number'] }}: {{ $replacement['start'] }}</li>@endforeach</ul><form method="post" action="{{ route('delivery.lifecycle',$enrolment->id) }}">@csrf<input type="hidden" name="action" value="resume"><input type="hidden" name="expected_version" value="{{ $enrolment->version }}"><input type="hidden" name="change" value="{{ $change->id }}"><button class="primary">Approve this schedule and resume</button></form>@endforeach
@endif</section>@endif
@endsection
