const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=fs.readFileSync('.archify-current-run','utf8').replace(/^\uFEFF/,'').trim();
const skill='C:/Users/Admin/.codex/skills/archify', cli=skill+'/bin/archify.mjs';
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n')};
const card=(title,...items)=>({dot:'cyan',title,items});
const meta=(id,title,viewBox)=>({title:id+' · '+title,output:id+'/diagram.html',quality_profile:'showcase',animation:'none',locale:'en',...(viewBox?{viewBox}:{})});
const edge=(from,to,label,variant='default')=>({id:from+'-to-'+to,from,to,label,variant});
const comp=(id,type,label,sublabel,x,y,w=210)=>({id,type,label,sublabel,pos:[x,y],size:[w,70]});
const save=(id,s)=>write(root+'/'+id+'/candidate.json',s);
const arch=(id,title,components,connections,boundaries,cards)=>save(id,{schema_version:1,diagram_type:'architecture',meta:meta(id,title,[1500,840]),components,connections,boundaries,cards});
const wf=(id,title,lanes,nodes,edges,mainPath,cards)=>save(id,{schema_version:2,diagram_type:'workflow',meta:meta(id,title),lanes:lanes.map(([id,label])=>({id,label})),nodes:nodes.map(([id,lane,col,type,label,sublabel])=>({id,lane,col,type,label,sublabel,width:170,height:64})),edges,mainPath,cards});
const flow=(id,title,nodes,flows,cards)=>save(id,{schema_version:1,diagram_type:'dataflow',meta:meta(id,title,[1500,850]),stages:['Sources','Validation','Owned state','Publication','Consumers'].map(label=>({label})),nodes:nodes.map(([id,stage,row,type,label,sublabel])=>({id,stage,row,type,label,sublabel,width:190,height:68})),flows,cards});
const life=(id,title,lanes,states,transitions,cards)=>save(id,{schema_version:1,diagram_type:'lifecycle',meta:meta(id,title,[1200,700]),lanes:lanes.map(([id,label])=>({id,label})),states:states.map(([id,lane,col,type,label,sublabel])=>({id,lane,col,type,label,sublabel,width:158,height:70})),transitions,cards});
if(process.argv[2]==='author'){
arch('D02','Proposed Proxmox deployment',[
comp('browser','external','Staff browser','HTTPS ingress only',40,360),comp('identity','security','Identity service VM','Shared authentik · assumed',40,110),comp('training-web','backend','Proxy + PHP web','Nginx / Laravel / PHP FPM',450,360),comp('evidence','database','Private evidence','Outside public root',450,110),comp('database','database','MariaDB','Application + queue + locks',860,360),comp('backup','external','Off-host backup','Encrypted · separate host',1240,360),comp('worker','backend','Worker / scheduler','systemd · same release',860,630),comp('external-services','external','AI APIs + SMTP','Outbound HTTPS / SMTP TLS',450,630),comp('primary-platform','external','Primary platform','Physical location unknown',1240,110)],
[edge('browser','training-web','HTTPS'),edge('browser','identity','OIDC + MFA','security'),edge('training-web','evidence','Private I/O'),edge('training-web','database','SQL / enqueue'),edge('database','worker','DB queue','dashed'),edge('worker','external-services','Outbound TLS'),edge('database','backup','Backup set','dashed'),edge('primary-platform','training-web','Scoped HTTPS')],
[{kind:'region',label:'Proposed Proxmox host · infrastructure owner',wraps:['training-web','evidence','database','worker'],pad:55},{kind:'security-group',label:'Training Linux VM · private services',wraps:['training-web','evidence','database','worker'],pad:25}],
[card('Sizing and owners','Training VM: 2 vCPU / 4 GB / 40–60 GB starting estimate; one VM is not high availability.','Infrastructure owner maintains VM, OS and backups; application owner maintains releases and queues.'),card('Separate identity','Identity service has its own vendor-managed data services and separate capacity. Identity owner maintains MFA and recovery.','Primary integration owner confirms location and private routing; database and files are never public.'),card('Recovery and operations','Off-host backup set includes DB, evidence, keys and IdP configuration. Proposed RPO 24h / RTO 4h needs an isolated restore drill.','Monitor queue/sync age, review backlog, spend, disk, SMTP bounces and backup freshness. Pilot: 100 members / 20 concurrent; measure p95 <500ms ordinary reads.')]);
arch('D03','cPanel alternative · NOT QUALIFIED',[
comp('browser','external','Staff browser','HTTPS ingress',40,350),comp('identity','security','External authentik','Separate service · OIDC + MFA',40,100),comp('training-web','backend','Public document root','Only Laravel public/',460,350),comp('private-app','backend','Private app + config','Code / secrets / evidence',460,100),comp('database','database','MariaDB','Private queue / locks / state',870,350),comp('cron','messagebus','Per-minute cron','Scheduler + overlap lock',1240,350),comp('worker','backend','Bounded CLI worker','Finite runtime · same release',870,630),comp('external-services','external','External integrations','AI / primary API / SMTP',460,630),comp('proxmox','cloud','Whole-app Proxmox','If capability gates fail',1240,100)],
[edge('browser','identity','OIDC','security'),edge('browser','training-web','HTTPS'),edge('training-web','private-app','Private I/O'),edge('training-web','database','SQL / enqueue'),edge('cron','worker','CLI start','dashed'),edge('database','worker','DB jobs','dashed'),edge('worker','external-services','HTTPS / SMTP'),edge('cron','proxmox','Gate failure','security')],
[{kind:'region',label:'Conditional cPanel account · host capabilities unverified',wraps:['training-web','private-app','database','worker','cron'],pad:28}],
[card('Qualification gates','Verify PHP/CLI/extensions, Composer builds, per-minute cron, shared locks, private storage, quotas and outbound HTTPS / SMTP TLS.','Provider timeout 90s < job timeout 120s < retry_after 180s; finite worker must finish one whole job. Verify extraction utilities and process limits.'),card('Failure decision','Unsupported runtime or utilities → move the whole application to Proxmox. No assumed hybrid worker dependency.','Prebuild assets. No Docker, Redis, root access, Node server or local identity service required.'),card('Environment and operations','Separate test DB, credentials, files, endpoints and SMTP sink. Synthetic data never enters production reports/export/mail.','Host capability owner verifies quotas and backups; application owner monitors queue lag, failures and restores before release.')]);
wf('D05','Submission and grading review',[['member','Member'],['app','Application / worker'],['review','Coordinator'],['recovery','Recovery / notification']],
[['draft','member',0,'frontend','Draft / autosave','Recoverable work'],['submit','member',1,'database','Submit attempt','Immutable receipt + hashes'],['grade','app',1,'messagebus','Queued grading','Quiz key or provisional AI'],['validate','app',2,'security','Validate grade','Rubric / evidence / arithmetic'],['review','review',2,'security','Review pending','Assigned coordinator'],['approve','review',3,'security','Approve / override','Exact version + reason'],['publish','review',4,'database','Approved result','KPI + adaptation + outbox'],['feedback','member',4,'frontend','Approved feedback','Appeal / human review'],['regrade','recovery',3,'backend','Regrade / resubmit','Separate attempts'],['failure','recovery',1,'backend','Technical failure','Preserve attempt · bounded retry'],['notify','recovery',2,'messagebus','Review notification','SMTP after provisional save']],
[edge('draft','submit','Submit'),edge('submit','grade','Queue after commit','dashed'),edge('grade','validate','Provisional result'),edge('validate','review','Persist valid result'),edge('review','approve','Human decision'),edge('approve','publish','Atomic approval'),edge('publish','feedback','Release feedback'),edge('review','regrade','Request changes'),{...edge('regrade','grade','New grading attempt'),role:'return'},edge('grade','failure','Provider / job failure','security'),{...edge('failure','grade','Bounded retry'),role:'return'},edge('review','notify','Queue mail','dashed')],
['draft','submit','grade','validate','review','approve','publish','feedback'],
[card('Immutable and fair','Resubmission creates a NEW submission; regrade creates a new grading attempt. Member appeal keeps original approval and uses another reviewer where possible.','No self approval. Concurrent review uses optimistic versions; overrides record reason. Only approved grades update official KPIs and normal API answers.'),card('Failure and notifications','Invalid criterion, evidence or schema returns for correction/regrade; no zero score on technical failure. Provider outage leaves approved lessons and autosave usable.','SMTP failures do not lose submission or review queue: retry/dedup, bounce alert, recheck recipient access, record ambiguous acceptance; reminders and overdue escalation.'),card('AI policy and cost','Two adapters + mock; per-task model/capability/privacy policies. Reserve cost before enqueue; reconcile tokens, rates and ambiguous timeout charges.','90s provider / 120s job / 180s retry_after; three transient retries, capped concurrency and explicit allowlisted fallback. No model grants approval.')]);
save('D06',{schema_version:1,diagram_type:'sequence',meta:{...meta('D06','Permission-scoped primary AI query',[1500,1020]),column_fit:'spread'},participants:[['user','external','Authorised user','Own / assigned scope'],['primary-platform','backend','Primary backend','Permitted tool orchestration'],['identity','security','Identity service','Assumed authentik'],['training-api','backend','Training API','Audience + policy enforcement'],['policy-store','database','Training data / policy','Private approved records']].map(([id,type,label,sublabel])=>({id,type,label,sublabel})),segments:[{from:155,to:335,label:'Delegation'},{from:355,to:600,label:'Allowed branch'},{from:620,to:865,label:'Denied / stale branch'}],messages:[['user','primary-platform',180,'Ask progress question','default'],['primary-platform','identity',230,'Exchange user delegation','security'],['identity','primary-platform',280,'Training audience token','return'],['primary-platform','training-api',380,'Scoped summary request','security'],['training-api','policy-store',430,'Fresh policy + approved facts','security'],['policy-store','training-api',480,'Permitted rows only','return'],['training-api','primary-platform',530,'Facts + provenance + data_as_of','return'],['primary-platform','user',580,'Answer from permitted tool result','return'],['primary-platform','training-api',670,'Invalid / stale / denied request','security'],['training-api','policy-store',720,'Check permission freshness','security'],['training-api','primary-platform',770,'401 / 403 / 404; no personal data','return'],['primary-platform','user',820,'Access unavailable; refresh needed','return']].map(([from,to,y,label,variant],i)=>({id:'message-'+(i+1),from,to,y,label,variant})),cards:[card('Server-enforced scope','Validate signature, issuer, audience, expiry, mapped user and caller; intersect scope, role, assignments, ownership, organisation and environment.','Filter before search, pagination and totals; exclude local_only, export_requested and synthetic records from primary retrieval.'),card('Fail closed and cache safely','Permission snapshot older than five minutes denies privileged/external personal retrieval. 401 invalid token; 403 missing operation scope; 404 inaccessible object.','Partition caches by identity + permission version, expire/invalidate on revocation and recheck before display.'),card('Credential boundary','Directory machine credentials are separate: no arbitrary user_id header or broad token fallback. OIDC + MFA login uses each app’s own client.','Frontier model gets only permitted tool results, no credentials or direct database access. Delegation integration remains unproven.') ]});
flow('D07','Directory sync and approved facts',[
['primary-directory',0,0,'external','Primary directory','People / groups owner'],['directory-gate',1,0,'security','Validate + dedup','Signature / version / ownership'],['member-directory',2,0,'database','Member directory','Verified ID + sync ledger'],['local-learning',3,0,'frontend','Local learning','Real local-only included'],['local-person',0,2,'frontend','Manual profile','local_only by default'],['promotion',1,2,'security','Promotion review','Duplicate check + request key'],['mapping',2,2,'backend','Verify mapping','Primary acknowledgement'],['approvals',0,4,'database','Training approvals','Application-owned facts'],['outbox',1,4,'messagebus','Transactional outbox','Version + event identity'],['outbound-gate',2,4,'security','Outbound policy','Linked · real · approved'],['delivery',3,4,'messagebus','Retry + reconcile','At-least-once + dead letter'],['primary-facts',4,4,'external','Primary facts','Consolidated approved view']],
[edge('primary-directory','directory-gate','Directory events','security'),edge('directory-gate','member-directory','Owned fields'),edge('member-directory','local-learning','Local access'),edge('local-person','promotion','Explicit export request','security'),edge('promotion','mapping','Ack + identity check'),edge('mapping','member-directory','Linked identity'),edge('local-person','member-directory','Local profile'),edge('approvals','outbox','Approved version','dashed'),edge('outbox','outbound-gate','Candidate event'),edge('outbound-gate','delivery','Allowed facts','security'),edge('delivery','primary-facts','Signed HTTPS','dashed')].map(e=>({...e,classification:'Personal data · scoped'})),
[card('Ownership and rejection','Primary owns imported people/groups; local cohorts and coordinator assignments remain app-owned. Training owns evidence and approval history.','Duplicate/stale events rejected; conflict queue handles incompatible versions. Suspension/tombstones revoke access and invalidate cache; freshness target five minutes.'),card('Promotion is explicit','Real local-only people train and appear in authorised local reports; no primary query/export. Synthetic records never cross production report, mail or integration boundaries.','Promotion timeout → reconcile original key. Ack plus verified mapping required before linked. Duplicate review returns to correction; history export is a separate action.'),card('Reliable and private','Outbox shares business transaction. Reconcile stable pages; cursor advances only after persistence. Every outbound retry rechecks linked/production/non-synthetic policy.','Private evidence: scan/quarantine, authorised download, no unrestricted URLs. Retention/erasure covers files, caches, exports and traces; holds and deletion ledger survive restore.')]);
life('D08','Enrolment lifecycle',[['main','Enrolment states'],['pause','Pause / resume'],['terminal','Terminal exit']],
[['onboarding','main',0,'start','Onboarding','Profile and calendar'],['ready','main',1,'waiting','Ready','Baseline approved'],['active','main',2,'active','Active','Approved lessons'],['completed','main',3,'success','Completed','Human final approval'],['paused','pause',0,'waiting','Paused','Preserve attempts'],['cancelled','terminal',0,'neutral','Cancelled','Terminal · history kept']],
[edge('onboarding','ready','Approve baseline'),edge('ready','active','Activation checks'),edge('active','completed','Evidence sufficient'),edge('active','paused','Approved leave'),edge('paused','active','Resume + rebase'),edge('active','cancelled','Cancel')],
[card('Readiness and completion','Reject activation until baseline content for every week is approved; current + next remain usable. Completion requires sufficient approved evidence, required tasks and coordinator confirmation.','4/6/8/10/12 blocks. Time spent never automatically proves competence or completes an enrolment.'),card('Calendar changes','Pause preserves active work and attempts. Resume previews shifted future dates and creates a calendar version; recompute holiday-aware cutoffs.','All programmes share one capacity calendar, 15–120 minutes per active day including assessment/revision. Do not rewrite completed history.'),card('Separate programme version state','Programme version: draft → generating → needs_review → approved → superseded; generation_failed returns to correction. These are not enrolment states.','Enrolment has one accountable coordinator. Permission and optimistic version checks apply to activation, pause, resume and completion.')]);
life('D09','Submission attempt lifecycle',[['main','Attempt progression'],['review','Review outcomes'],['failure','Recoverable failure'],['terminal','Terminal withdrawal']],
[['draft','main',0,'start','Draft','Autosave'],['submitted','main',1,'active','Submitted','Immutable receipt'],['queued','main',2,'active','Queued','Durable job'],['grading','main',3,'active','Grading','Provisional only'],['review-pending','main',4,'decision','Review pending','Coordinator gate'],['approved','review',2,'success','Approved','Immutable decision'],['changes-requested','review',1,'waiting','Changes requested','New submission required'],['technical-failure','failure',1,'failure','Technical failure','Bounded retry'],['withdrawn','terminal',0,'neutral','Withdrawn','Before approval only']],
[edge('draft','submitted','Submit'),edge('submitted','queued','Commit + enqueue'),edge('queued','grading','Claim job'),edge('grading','review-pending','Validated result'),edge('review-pending','approved','Human approval'),edge('review-pending','changes-requested','More evidence'),edge('grading','technical-failure','Job failure'),edge('technical-failure','grading','Retry budget'),edge('queued','withdrawn','Allowed withdrawal')],
[card('Attempt identity','Resubmission starts a NEW draft/attempt linked to the old one; changes_requested never mutates an immutable submission.','Regrade from review_pending creates a new grading attempt on this submission, then returns to review_pending. Approved decisions can only be superseded with reason.'),card('Review and appeal','Approve/override requires assigned alternate reviewer when self-enrolled; optimistic conflict prevents stale simultaneous decisions.','Appeal opens a separate review preserving the original approval. Approved and withdrawn are terminal for this decision; approved evidence drives KPIs.'),card('Failure / withdrawal','Technical failure is not a zero score: preserve evidence and use bounded retry or human recovery. No submission data is lost when SMTP fails.','Withdrawal is policy-permitted only before approved review, including submitted, queued, grading and review_pending; cancel jobs and preserve audit.')]);
wf('D10','Weekly adaptation and freeze cutoff',[['policy','Deterministic application policy'],['draft','AI proposal / coordinator'],['fallback','Baseline fallback / calendar']],
[['evidence','policy',0,'database','Approved Week N','Snapshot grade / KPI versions'],['target','policy',1,'backend','Select N+2','Within programme duration'],['eligible','policy',2,'security','Eligible target?','Before cutoff · no activity'],['proposal','draft',2,'messagebus','AI proposal','Within capacity / target'],['validate','draft',3,'security','Validate proposal','Calendar / schema / prerequisites'],['review','draft',4,'security','Coordinator review','Diff + reason + evidence'],['publish','policy',4,'database','Recheck + publish','Atomic version / access check'],['notify','policy',5,'frontend','Notify member','Keep old version / event'],['later','fallback',2,'backend','Keep baseline','Select later eligible target'],['support','fallback',3,'frontend','Final support','No target → follow-on proposal'],['rebase','fallback',1,'backend','Leave / rebase','Version future calendar']],
[edge('evidence','target','Evidence block + 2'),edge('target','eligible','Candidate block'),edge('eligible','proposal','Eligible','dashed'),edge('proposal','validate','Draft replacement'),edge('validate','review','Valid'),edge('review','publish','Approve exact diff'),edge('publish','notify','Commit + event'),edge('eligible','later','Locked / started'),edge('publish','later','Late / stale conflict'),edge('later','support','None remains'),{...edge('later','target','Try later block'),role:'return'},edge('rebase','target','Recompute cutoff')],
['evidence','target','eligible','proposal','validate','review','publish','notify'],
[card('Worked calendar · Asia/Manila','W1 starts 5 Oct 2026; Friday evidence reviewed Monday W2. W3 starts 19 Oct; freeze Thursday 15 Oct at 17:00. Approval 14 Oct revises W3; W2 stays unchanged.','Use evidence N+2, never current_week+2. Late approval 16 Oct keeps W3 baseline and tries W4. Final two blocks route to support, never Week 5 of a four-week plan.'),card('Readiness is not permanent freeze','Whole-programme baseline is approved before activation. Current + next are ready; future preview is revisable before cutoff with visible notice.','Freeze at second business day before start, 17:00 local, or immediately on early start/activity. Holidays shift cutoff; no immediate weekend review required.'),card('Transactional recheck','At approval verify evidence, calendar, policy, base version, reviewer scope, no activity and shared daily capacity. Invalid draft returns for correction; stale review retains baseline.','Targets/KPI definitions remain human-owned. Required changes need approval; emergency current-content correction needs explicit reason and member notice.')]);
flow('D11','KPI lineage and improvement suggestions',[
['assessment',0,0,'database','Source assessment','Original scale + provenance'],['observations',0,2,'database','Approved rubric','Criterion evidence only'],['normalise',1,1,'backend','Normalise + compare','Evidence / sample checks'],['definitions',1,4,'security','Human KPI definition','Effective-dated targets'],['calculate',2,1,'backend','Versioned calculation','Formula + evidence lineage'],['snapshot',3,1,'database','Approved snapshot','Sufficient evidence only'],['dashboards',4,0,'frontend','Local dashboards','Member / coordinator scope'],['primary-api',4,2,'external','Permitted primary API','Approved linked facts'],['suggestions',2,4,'backend','AI suggestions','Gaps + remaining capacity'],['approval',3,4,'security','Coordinator gate','Required work changes'],['future-work',4,4,'frontend','Feasible actions','Advisory / approved changes']],
[edge('assessment','normalise','Source scale'),edge('observations','normalise','Approved evidence'),edge('normalise','calculate','Comparable sample'),edge('definitions','calculate','Formula + target'),edge('calculate','snapshot','Versioned value'),edge('snapshot','dashboards','Local scope','security'),edge('snapshot','primary-api','Linked real only','security'),edge('calculate','suggestions','Gap + capacity'),edge('suggestions','approval','Proposed change'),edge('approval','future-work','Human approval')].map(e=>({...e,classification:'Training evidence · scoped'})),
[card('Measure what and why','Every KPI records owner, what/why, baseline/date, target, formula, unit/direction, evidence, cadence, sample minimum and version.','Keep participation, demonstrated competence and workplace outcome separate. Weighted criterion percentages sum with weights = 1; incomparable scales need explicit mapping.'),card('Honest interpretation','Insufficient samples or missing baseline → insufficient_evidence, never zero. Effective-dated target changes never rewrite old snapshots.','Local reports include genuine local-only members; primary API excludes local-only/pending/synthetic. Synthetic data stays out of all production totals.'),card('Useful suggestions and privacy','One to three feasible suggestions fit remaining time. Current advice adds no required work; required changes pass coordinator gate and D10 freeze policy.','Preserve provenance and calculation versions. Retention/holds/erasure extend to derived snapshots and exports. No public ranking or unsupported employment decisions.')]);
}
function run(args,out){const result=cp.spawnSync(process.execPath,[cli,...args],{encoding:'utf8',cwd:path.resolve(root),timeout:120000});write(root+'/'+out,result.stdout||'');write(root+'/'+out+'.execution.json',{command:[process.execPath,cli,...args],cwd:path.resolve(root),exitCode:result.status,error:result.error?.message,stderr:result.stderr});return result;}
if(['validate','deliver','visual-check'].includes(process.argv[2])){const mode=process.argv[2];for(const id of (process.argv.slice(3).length?process.argv.slice(3):Array.from({length:11},(_,i)=>'D'+String(i+1).padStart(2,'0')))){const s=JSON.parse(fs.readFileSync(root+'/'+id+'/candidate.json'));let args=mode==='visual-check'?[mode,id+'/diagram.html','--json']:[mode,s.diagram_type,id+'/candidate.json',...(mode==='deliver'?[id+'/diagram.html']:[]),'--quality','showcase','--json'];if(mode==='visual-check'&&!fs.existsSync(root+'/'+id+'/diagram.html'))continue;let r=run(args,id+'/'+mode+'-'+Date.now()+'.json'); console.log(id,mode,r.status,(r.stdout||'').slice(0,mode==='validate'?180:70));}}
