<?php

use App\Http\Controllers\AdministrationController;
use App\Http\Controllers\AiController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\DocumentExtractionController;
use App\Http\Controllers\LearningController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\ProgressionController;
use App\Http\Controllers\SandboxApiController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\WorkspaceController;
use App\Http\Middleware\TrainingSession;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route('dashboard'));
Route::get('/login', [SessionController::class, 'create'])->name('login');
Route::post('/login', [SessionController::class, 'store'])->middleware('throttle:10,1')->name('login.store');
Route::post('/logout', [SessionController::class, 'destroy'])->name('logout');
Route::middleware(TrainingSession::class)->group(function () {
    Route::get('/files/{id}/extraction', [DocumentExtractionController::class, 'show'])->name('documents.show');
    Route::post('/files/{id}/extraction', [DocumentExtractionController::class, 'request'])->middleware('throttle:10,1')->name('documents.request');
    Route::post('/extractions/{id}/review', [DocumentExtractionController::class, 'review'])->name('documents.review');
    Route::get('/reviews', [DeliveryController::class, 'reviews'])->name('reviews.show');
    Route::get('/notifications', [NotificationsController::class, 'show'])->name('notifications.show');
    Route::post('/notifications', [NotificationsController::class, 'preference'])->name('notifications.preference');
    Route::get('/administration', [AdministrationController::class, 'show'])->name('administration.show');
    Route::post('/administration', [AdministrationController::class, 'act'])->name('administration.act');
    Route::get('/enrolments/{id}/progress', [ProgressionController::class, 'show'])->name('progress.show');
    Route::post('/enrolments/{id}/progress', [ProgressionController::class, 'act'])->name('progress.act');
    Route::get('/enrolments/{id}/learn', [DeliveryController::class, 'show'])->name('delivery.show');
    Route::post('/enrolments/{id}/activate', [DeliveryController::class, 'activate'])->name('delivery.activate');
    Route::post('/enrolments/{id}/lifecycle', [DeliveryController::class, 'lifecycle'])->name('delivery.lifecycle');
    Route::get('/lessons/{id}/{index}', [DeliveryController::class, 'lesson'])->whereNumber('index')->name('delivery.lesson');
    Route::post('/lessons/{id}/{index}/save', [DeliveryController::class, 'save'])->whereNumber('index')->name('delivery.save');
    Route::post('/lessons/{id}/{index}/quiz', [DeliveryController::class, 'quiz'])->whereNumber('index')->name('delivery.quiz');
    Route::post('/lessons/{id}/{index}/submit', [DeliveryController::class, 'submit'])->whereNumber('index')->name('delivery.submit');
    Route::post('/blocks/{id}/early-start', [DeliveryController::class, 'early'])->name('delivery.early');
    Route::get('/submissions/{id}', [DeliveryController::class, 'receipt'])->name('submission.show');
    Route::post('/submissions/{id}/review', [DeliveryController::class, 'review'])->name('submission.review');
    Route::get('/settings/ai', [AiController::class, 'settings'])->name('ai.settings');
    Route::post('/settings/ai', [AiController::class, 'policy'])->name('ai.policy');
    Route::post('/settings/ai/{id}/reconcile', [AiController::class, 'reconcile'])->name('ai.reconcile');
    Route::post('/enrolments/{id}/generation', [AiController::class, 'request'])->middleware('throttle:10,1')->name('ai.request');
    Route::get('/generation/{id}', [AiController::class, 'show'])->name('ai.show');
    Route::get('/enrolments/{id}/onboarding', [LearningController::class, 'onboarding'])->name('onboarding.show');
    Route::post('/enrolments/{id}/onboarding/calendar', [LearningController::class, 'calendar'])->name('onboarding.calendar');
    Route::post('/enrolments/{id}/onboarding/{step}', [LearningController::class, 'save'])->name('onboarding.save');
    Route::get('/enrolments/{id}/curriculum', [LearningController::class, 'show'])->name('plans.show');
    Route::post('/enrolments/{id}/curriculum', [LearningController::class, 'create'])->name('plans.create');
    Route::post('/enrolments/{id}/curriculum/edit', [LearningController::class, 'edit'])->name('plans.edit');
    Route::post('/enrolments/{id}/curriculum/review', [LearningController::class, 'review'])->name('plans.review');
    Route::get('/dashboard', [WorkspaceController::class, 'index'])->name('dashboard');
    Route::get('/people', [WorkspaceController::class, 'people'])->name('people');
    Route::get('/enrolments/{id}', [WorkspaceController::class, 'show'])->name('enrolments.show');
    Route::post('/enrolments/{id}/check', [WorkspaceController::class, 'check'])->name('enrolments.check');
    Route::post('/enrolments/{id}/files', [WorkspaceController::class, 'upload'])->middleware('throttle:20,1')->name('files.upload');
    Route::get('/files/{id}', [WorkspaceController::class, 'download'])->name('files.download');
    Route::get('/jobs/{id}', [WorkspaceController::class, 'job'])->name('jobs.show');
});
// Read-only sandbox contract proof. Live delegated identity is deliberately not advertised as implemented.
Route::get('/api/v1/me/training', [SandboxApiController::class, 'summary'])->middleware('throttle:60,1');
Route::get('/api/v1/training/changes', [SandboxApiController::class, 'changes'])->middleware('throttle:60,1');
Route::get('/api/v1/members/{memberId}/summary', [SandboxApiController::class, 'summary'])->middleware('throttle:60,1');
