@extends('layouts.app')
@section('title','Administration')
@section('content')
<h1>People and programme administration</h1><p>Create local cohorts, assign responsibility, and review integration state. Administrative access does not reveal submission bodies.</p>
<section class="panel"><h2>Add a local person</h2><form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="person"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Role<select name="role"><option value="member">Member</option><option value="coordinator">Coordinator</option></select></label><label>Record type<select name="synthetic"><option value="1">Synthetic sandbox person (example.invalid email)</option><option value="0">Real local-only person (live identity required)</option></select></label><label>Reason<input name="reason" minlength="8" required></label><button class="primary">Create person</button></form></section>
<section class="panel"><h2>Create cohort</h2><form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="group"><label>Cohort name<input name="name" required></label><label>Reason<input name="reason" minlength="8" required></label><button class="secondary">Create local cohort</button></form></section>
<section class="panel"><h2>People and assignments</h2>@foreach($people as $person)<details><summary>{{ $person->name }} · {{ $person->role }} · {{ $person->active?'Active':'Inactive' }} · {{ $person->sync_policy }}</summary><p>{{ $person->origin }} · {{ $person->is_synthetic?'Synthetic':'Real' }} · permission version {{ $person->permission_version }}</p>
<form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="assignment"><input type="hidden" name="person" value="{{ $person->id }}"><input type="hidden" name="expected" value="{{ $person->permission_version }}"><label>Cohort<select name="group">@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }} ({{ $group->origin }})</option>@endforeach</select></label><label>Assignment<select name="assignment_type"><option value="member">Member</option><option value="coordinator">Coordinator responsibility</option></select></label><label>Change<select name="active"><option value="1">Assign</option><option value="0">Remove</option></select></label><label>Reason<input name="reason" minlength="8" required></label><button class="secondary">Update assignment</button></form>
@if($person->origin==='manual' && $person->active && $person->id!==auth()->id())<form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="deactivate"><input type="hidden" name="person" value="{{ $person->id }}"><input type="hidden" name="expected" value="{{ $person->permission_version }}"><label>Deactivation reason<input name="reason" minlength="8" required></label><button class="secondary">Deactivate local person</button></form>@endif
@if(!$person->is_synthetic && $person->origin==='manual' && $person->sync_policy==='local_only')<form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="promote"><input type="hidden" name="person" value="{{ $person->id }}"><input type="hidden" name="key" value="{{ Str::uuid() }}"><label>Verified identity and duplicate review rationale<input name="reason" minlength="8" required></label><button class="secondary">Prepare promotion</button></form>@endif
@if(!$person->is_synthetic && $person->sync_policy==='linked' && !$person->export_training_history)<form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="history"><input type="hidden" name="person" value="{{ $person->id }}"><label>Historical training export approval reason<input name="reason" minlength="8" required></label><button class="secondary">Authorise history export</button></form>@endif
</details>@endforeach</section>
<section class="panel"><h2>Create enrolment</h2><form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="enrol"><label>Member<select name="person">@foreach($people as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label><label>Accountable coordinator<select name="coordinator">@foreach($people->where('role','coordinator') as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label><label>Cohort<select name="group">@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</select></label><label>Programme title<input name="title" required></label><label>Reason<input name="reason" minlength="8" required></label><button class="primary">Create enrolment</button></form></section>
<section class="panel"><h2>Appeal assignments</h2>@forelse($appeals as $appeal)<p>Appeal {{ $appeal->id }} · {{ $appeal->reviewer_id?'Assigned':'Awaiting independent reviewer' }}</p><form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="appeal"><input type="hidden" name="appeal" value="{{ $appeal->id }}"><label>Alternate coordinator<select name="coordinator">@foreach($people->where('role','coordinator') as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label><label>Assignment reason<input name="reason" minlength="8" required></label><button class="secondary">Assign independent review</button></form>@empty<p>No open appeals.</p>@endforelse</section>
<section class="panel"><h2>Promotion ledger</h2><p>No primary-platform service is configured. Prepared requests remain local and excluded from external retrieval.</p>@forelse($promotions as $promotion)<p>{{ $promotion->person->name }} · {{ $promotion->status }} · key {{ $promotion->idempotency_key }}</p>@if(in_array($promotion->status,['prepared','ambiguous']))<form method="post" action="{{ route('administration.act') }}">@csrf<input type="hidden" name="action" value="{{ $promotion->status==='ambiguous'?'reconcile':'send' }}"><input type="hidden" name="promotion" value="{{ $promotion->id }}"><label>Review reason<input name="reason" minlength="8" required></label><button class="secondary">{{ $promotion->status==='ambiguous'?'Reconcile original key':'Send prepared request' }}</button></form>@endif @empty<p>No promotions.</p>@endforelse</section>
@endsection
